#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# based on https://gist.githubusercontent.com/siddharthkrish/32072e6f97d7743b1a7c47d76d2cb06c/raw/0228b9288b0ea7290d32e66189c7b7729e5e0f14/version.sh

# shellcheck disable=SC1090
# shellcheck disable=SC1091
# shellcheck source=/dev/null

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/git-src-common"

function usage()
{

cat << EOF
Usage:

\`\`\`bash

  $BIN VERSION [MAJOR|MINOR|PATCH]

\`\`\`

Increment \`VERSION\` according
[_Semantic Versioning_](https://semver.org/spec/v2.0.0.html)

Example:

\`\`\`bash

  $BIN v0.1.0 PATCH
  v0.1.1

  $BIN v0.1.0 MINOR
  v0.2.0

  $BIN v0.1.0 MAJOR
  v1.0.0

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

VERSION="$1"
NAME="$(echo "$1" | grep -Eo '[a-z\_]+')"
MAJOR=0
MINOR=0
PATCH=0

# break down the version number into it's components
REGEX="([0-9]+).([0-9]+).([0-9]+)"
if [[ $VERSION =~ $REGEX ]]
then
  MAJOR="${BASH_REMATCH[1]}"
  MINOR="${BASH_REMATCH[2]}"
  PATCH="${BASH_REMATCH[3]}"
fi

# check paramater to see which number to increment
if [[ "$2" == "MINOR" ]]; then
  MINOR="$(echo "$MINOR + 1" | bc)"
  PATCH='0'
elif [[ "$2" == "PATCH" ]]; then
  PATCH="$(echo "$PATCH + 1" | bc)"
elif [[ "$2" == "MAJOR" ]]; then
  MAJOR="$(echo "$MAJOR + 1" | bc)"
  MINOR='0'
else
  usage
fi

# echo the new version number
printf "%s%s.%s.%s" "$NAME" "$MAJOR" "$MINOR" "$PATCH"
