#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

find -L . -type d -name .git 2>/dev/null | cut -c 3- | while read -r D
do

  CFG="$D/config"
  [[ -e "$CFG" ]] || continue
  export GIT_DIR="$D"

URL="$(git remote get-url origin 2>/dev/null \
  | sed 's/git@//g' \
  | sed 's/\.git$//g'
)"

  [[ -z "$URL" ]] && continue
  DIR="$(echo "$D" | sed 's/\/.git$//g')"
  printf "%-72s %s\\n" "$DIR" "$URL"

done | sort -bu
