#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2021 Osiris Alejandro Gomez <osiux@osiux.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

TMP1='/tmp/.git-repos.1.tmp'
TMP2='/tmp/.git-repos.2.tmp'
TMP3='/tmp/.git-repos.3.tmp'
REPOS="$HOME/.git-repos"

[[ -e $PWD/.git-repos ]] && REPOS="$PWD/.git-repos"

> "$TMP1"
> "$TMP2"

sort -k1 "$REPOS" | sort -u | while read n r
do
  dir=$(echo "$n" | grep -o / | head -1)
  if [ "$dir" = "/" ]
  then
    printf "%-72s %s\n" "$n" "$r" >> "$TMP1"
  else
    printf "%-72s %s\n" "$n" "$r" >> "$TMP2"
  fi
done

sort -u "$TMP1"  > "$REPOS"
sort -u "$TMP2" >> "$REPOS"
rm -f "$TMP1" "$TMP2"
