#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2022 Osiris Alejandro Gomez <osiux@osiux.com>
# Copyright (C) 2022 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1091
# shellcheck disable=SC1090
# shellcheck source=/dev/null

DIR_BIN="$(dirname "$0")" && source "$DIR_BIN/git-src-common"

function usage()
{
cat << EOF

## \`$BIN\` Generate CHANGELOG based on tag diff

### Usage

\`\`\`bash

  $BIN [CHANGELOG.md]

\`\`\`

### Example

\`\`\`bash

  $BIN

  GENERATE CHANGELOG.md

\`\`\`

### Defaults

| _variable_     | _default value_                                              |
|----------------|--------------------------------------------------------------|
| \`CHANGELOG   \` | \`CHANGELOG.md                                              \` |
| \`DATE_REGEX  \` | \`^[0-9]{4}-[0-9]{2}-[0-9]{2}                               \` |
| \`NAME        \` | \`directory name                                            \` |
| \`TITLE       \` | \`uppercase directory name + CHANGELOG                      \` |
| \`SEMVER      \` | \`[Semantic Versioning](https://semver.org/spec/v2.0.0.html)\` |
| \`REPO_URL    \` | \`git remote get-url origin                                 \` |
| \`IGNORE_REGEX\` | \`Merge (branch|tag)                                        \` |

### Example Output Format

\`\`\`md

# [_GIT-BASH-UTILS CHANGELOG_](https://gitlab.com/osiux/git-bash-utils)

 - this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html)

## [\`Unreleased - 2022-08-31\`](https://gitlab.com/osiux/git-bash-utils/-/compare/3b75889...develop)

### \`datediff\`

- calculate the number of days between 2 dates (ISO 8601)

\`\`\`

EOF
exit 0
}

function subject_del_issue()
{
  echo "$1" \
    | sed "s/\(REL\|FIX\) \#[0-9]\+ //g" \
    | sed 's/^ \+\-//g; s/^\- //g'
}

function git_log_subject()
{
  local ISSUE SHASH SUBJECT

  SHASH="$1"
  SUBJECT="$(subject_del_issue "$2")"
  ISSUE="$(git-commit-getissue "$SHASH")"
  ISSUE="${ISSUE%% *}"

  if [[ -z "$ISSUE" ]]
  then
    printf "%s %s\\n"    '-' "$SUBJECT"
  else
    printf "%s %s %s\\n" '-' "$ISSUE" "$SUBJECT"
  fi
}

function params()
{

  [[ "$1" =~ ^[-]+(h|help)   ]] && usage

  [[ -d '.git'               ]] || die "NOT FOUND VALID GIT REPOSITORY"
  [[ -e '.changelog'         ]] && source .changelog

  [[ -n "$CHANGELOG"         ]] || CHANGELOG='CHANGELOG.md'
  [[ -z "$1"                 ]] || CHANGELOG="$1"

}

function defaults()
{

  [[ -n "$DATE_REGEX"        ]] || DATE_REGEX='^[0-9]{4}-[0-9]{2}-[0-9]{2}'
  [[ -n "$NAME"              ]] || NAME="$(echo "$PWD" | rev | cut -d/ -f1 | rev)"
  [[ -n "$TITLE"             ]] || TITLE="${NAME^^} CHANGELOG"
  [[ -n "$SEMVER"            ]] || SEMVER='[Semantic Versioning](https://semver.org/spec/v2.0.0.html)'
  [[ -n "$REPO_URL"          ]] || REPO_URL="$(git-remote-geturl)"
  [[ -n "$IGNORE_REGEX"      ]] || IGNORE_REGEX='Merge (branch|tag)'
  [[ -n "$REGEX_TAG_EXCLUDE" ]] || REGEX_TAG_EXCLUDE='REGEX_TAG_EXCLUDE'
  [[ -n "$REGEX_TAG_VERSION" ]] || REGEX_TAG_VERSION='[0-9]+\.[0-9]+\.[0-9]+'
  [[ -n "$REGEX_COMMIT"      ]] || REGEX_COMMIT='^[a-f0-9]{6,8}'
  [[ -n "$REGEX_PREFIX"      ]] || REGEX_PREFIX='[a-zA-Z/\.\-]+:'

}

function temporal()
{
  LOG="$(mktemp)"
  LOG_NO_PREFIX="$(mktemp)"
  LOG_PREFIX="$(mktemp)"
  PREFIXES="$(mktemp)"
  TAGS="$(mktemp)"
  TMP="$(mktemp)"
}

function clean()
{
  rm -f "$LOG"
  rm -f "$TMP"
  rm -f "$TAGS"
  rm -f "$PREFIXES"
  rm -f "$LOG_NO_PREFIX"
  rm -f "$LOG_PREFIX"
}

function get_log_from_to()
{

  # get commits log and remove (REL|FIX) #ISSUE1 #ISSUE2 in Subject
  git log --oneline --pretty --format="%h %s" "$TO"..."$FROM"                    \
    | sed 's/\(#[0-9]\+\) #[0-9]\+/\1/g; s/\(REL\|FIX\) #[0-9]\+//Ig; s/ \+/ /g' \
    | sed -r 's/(^[0-9a-f]{6,8}) (\-|:) /\1 /g'                                  \
    | grep -v Squashed                                                           \
    | grep -vE "$IGNORE_REGEX"                                                   > "$LOG"

}

function get_log_no_prefix()
{
  grep -vE "$REGEX_COMMIT $REGEX_PREFIX" "$LOG" > "$LOG_NO_PREFIX"
}

function get_log_prefix()
{
  grep -E "$REGEX_COMMIT $REGEX_PREFIX" "$LOG" > "$LOG_PREFIX"
}

function get_commits_no_prefix()
{
  while read -r SHASH SUBJECT
  do

    git_log_subject "$SHASH" "$SUBJECT"

  done < "$LOG_NO_PREFIX" | awk '!seen[$0]++'
  printf "\\n"
}

function get_prefixes()
{
  grep -E "$REGEX_COMMIT $REGEX_PREFIX" "$LOG_PREFIX" \
    | awk '{print $2}'                                \
    | sort -u                                         > "$PREFIXES"
}

function get_commits_prefix()
{
  while read -r PREFIX
  do

    printf "### \`%s\`\\n\\n" "${PREFIX//:/}"

    grep "$PREFIX" "$LOG_PREFIX" | while read -r SHASH PREFIX SUBJECT
    do

      git_log_subject "$SHASH" "$SUBJECT"

    done | awk '!seen[$0]++'

    printf "\\n"

  done < "$PREFIXES"
}

function get_commits_first()
{
  git rev-list --max-parents=0 HEAD \
    | cut -c -7                     > "$TAGS"
}

function get_tags_from()
{
  git tag --sort version:refname    \
    | grep -vE "$REGEX_TAG_EXCLUDE" \
    | awk '{print $1}'              >>"$TAGS"
}

function get_tags_to()
{
  tail -n+2 "$TAGS"                 > "$TMP"
}

function join_tags_from_to()
{
  paste "$TAGS" "$TMP" | tac | sponge "$TAGS"
}

function filter_tags()
{
  grep -E "$REGEX_TAG_VERSION" "$TAGS" | sponge "$TAGS"
}

function get_tags()
{
  get_commits_first
  get_tags_from
  get_tags_to
  join_tags_from_to
  filter_tags
}

function show_title()
{
  printf "# [_%s_](%s)\\n\\n" "$TITLE" "$REPO_URL"
  [[ -z "$SEMVER" ]] \
    || printf " - %s\\n" "this project adheres to $SEMVER"
  printf "\\n"
}

function changelog_generate()
{

  show_title

while read -r FROM TO
do

  # use develop as Unreleased version
  [[ -z "$TO" ]] && TO='develop'

  # get diff between tags
  git diff --name-only "$TO" "$FROM" > "$TMP"

  DATE="$(git log -1 --format='%ci' "$TO" | grep -Eo "$DATE_REGEX")"
  TAG_URL="${REPO_URL//.git/}/-/compare/$FROM...$TO"
  RELEASE="${TO//develop/Unreleased}"

  TAG_NOTE="_$(git tag -n1 "$TO" | sed "s/$TO\ \+//g")_"
  TAG_NOTE="${TAG_NOTE//__/}"
  [[ -z "$TAG_NOTE" ]] || TAG_NOTE=" $TAG_NOTE"

  # subtitle for release
  printf "## [\`%s - %s\`](%s)%s\\n\\n" \
         "$RELEASE" "$DATE" "$TAG_URL" "$TAG_NOTE"

  get_log_from_to
  get_log_no_prefix
  get_log_prefix
  get_commits_no_prefix
  get_prefixes
  get_commits_prefix

done < "$TAGS"

}

function main()
{

  temporal
  defaults
  params "$@"
  get_tags
  # generate and overwrite CHANGELOG
  changelog_generate \
    | sed '${/^$/d;}' > "$CHANGELOG" \
    && echo "GENERATE $CHANGELOG"
  clean

}

main "$@"
