#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2021 Osiris Alejandro Gomez <osiux@osiux.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

[[ ! -z "$1" ]] && cd "$1"
[[ ! -d .git ]] && exit 1

git remote | while read -r REMOTE
do

URL="$(git remote get-url "$REMOTE"              \
  | sed 's/git@//g'                              \
  | sed 's/github:/https:\/\/github.com\//g'     \
  | sed 's/github.com:/https:\/\/github.com\//g' \
  | sed 's/gitlab.com:/https:\/\/gitlab.com\//g' \
  )"

[[ "$URL" =~ github.com ]] && REMOTE='github'
[[ "$URL" =~ gitlab.com ]] && REMOTE='gitlab'

printf "[[%s][%s]]\n" "$URL" "$REMOTE"

done
