#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2022 Osiris Alejandro Gomez <osiux@osiux.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC2034

# DON'T OVERWRITE GIT VARIABLES LIKE GIT_DIR
# https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables

RED="$(tput setaf 196)"
GREEN="$(tput setaf 46)"
NORMAL="$(tput sgr0)"
DIR_REAL="$(realpath "$DIR_BIN")"
DIR_BASE="$(dirname "$DIR_REAL")"
BIN="$(basename "$0")"

die ()
{
  printf "%s\\n" "${RED}[ERROR] $1 $NORMAL"
  [[ "$ERROR_SHOW_USAGE" -eq 1 ]] && usage
  exit 1
}

success ()
{
  printf "%s\\n" "${GREEN}[OK] $1 $NORMAL" && exit 0
}

stderror ()
{
  echo >&2 "$1"
}
