#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2019 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

[[ -z "$1"        ]] && exit 1
[[ -z "$2"        ]] && exit 1
[[ -d "$PWD/.git" ]] || exit 1

OLD="$1"
NEW="$2"

git tag "$NEW" "$OLD"
git tag -d "$OLD"

git push origin ":refs/tags/$OLD"
git push --tags

echo "git pull --prune --tags"
