#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2014 Osiris Alejandro Gomez <osiux@osiux.com.ar>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

REPOS=$HOME'/.git-repos'

white='[0m'
green='[01;32m'
red='[01;31m'
yellow='[01;33m'

CLONE=0
PUSH=0
PULL=0
SHOW_LOG=0
SHOW_TIME=0
FILTER=''
EXCLUDE=''

test -e $REPOS
OK=$?

if [ $OK -ne 0 ]
then
  echo ERROR $REPOS not found
  exit 1
fi

while getopts "cf:gltsx:" OPTION
do
  case $OPTION in
    c)
      CLONE=1
      ;;
    f)
      FILTER=$OPTARG
      ;;
    g)
      SHOW_LOG=1
      ;;
    l)
      PULL=1
      ;;
    s)
      PUSH=1
      ;;
    t)
      SHOW_TIME=1
      ;;
    x)
      EXCLUDE=$OPTARG
      ;;
  esac
done

echo

if [ -z $FILTER ]
then
  if [ -z $EXCLUDE ]
  then
    GIT_REPOS=$(grep -v ^# $REPOS)
  else
    GIT_REPOS=$(grep -v ^# $REPOS | grep -v $EXCLUDE)
  fi
else
  if [ -z $EXCLUDE ]
  then
    GIT_REPOS=$(egrep "$FILTER" $REPOS | grep -v ^#)
  else
    GIT_REPOS=$(egrep "$FILTER" $REPOS | grep -v ^# | egrep -v $EXCLUDE)
  fi
fi


echo "$GIT_REPOS" | sort | while read R
do
  cd ~
  DIR=$(echo $R | awk '{print $1}')
  GIT=$(echo $R | awk '{print $2}')

  echo ${white}

  if [ ! -d $DIR ]
  then
    if [ $CLONE -eq 1 ]
    then
      git clone $GIT $DIR
    else
      S=${red}'✖'
      echo ' '${S}${yellow} ${DIR} ${red}'NOT FOUND'${green}
      continue
    fi
  fi


  if [ $PUSH -eq 1 ]
  then
    cd $DIR
    HTTPS=$(egrep -o "$DIR\ +https" $REPOS | awk '{print $2}')
    [ ! "$HTTPS" = "https" ] && git push -q 2>/dev/null 1>/dev/null
  fi
  
  if [ $PULL -eq 1 ]
  then
    cd ~ && cd $DIR && git pull -q 2>/dev/null 1>/dev/null
  fi

  E=$(echo $?)

  if [ $E -eq 0 ]
  then
    S=${green}'✔'
  else
    S=${red}'✖'
  fi

  cd ~ && cd $DIR && BAR=$(git-streak)

  if [ $SHOW_TIME -eq 1 ]
  then
      HOURS=$(git log | egrep -o '@(.*)[0-9]{2}:[0-9]{2}' | tr -d '@ ' | awk 'function m(h) {split(h,A,":");return A[1]*60+A[2]} {t+=m($1)} END {printf "%02d:%02d",t/(60),t%60}')

      printf " %s%s %s %7s %s\n" $S $yellow $BAR $HOURS $DIR
  else
      echo ' '${S}${yellow}' '${BAR}' '${DIR}
  fi

  if [ $SHOW_LOG -eq 1 ]
  then
    LOG=$(git log -1 --topo-order --date=iso --pretty --format="%h %ad %ae %s" | sed s/:[0-9]*\ -[0-9]*\ /\ /g | sed s/@[a-z.\(\)]*/\\\t/g)
    echo -e "${white}\t  "$LOG
  fi
done

echo $white

