#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2014 Osiris Alejandro Gomez <osiux@osiux.com.ar>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

TODAY=`date +%Y-%m-%d`
LIMIT=`date --date='-30 days' +%Y-%m-%d`
GIT_DAYS=`git log --date=iso --since $LIMIT | grep Date | awk '{print $2}' | sort -u`
BAR=''
LAST_COMMIT=0
LAST_NO_COMMIT=0

green='[01;32m'
red='[01;31m'
white='[0m'

bar ()
{
	t=$2
	n=$1
	p=`echo "scale=2;($n/$t)*100" | bc`
	i=`echo $p | cut -d\. -f1`
	m=$(($i/5))

	if [ $i -eq 0 ]
	then
		exit
	fi

	if [ $i -lt 2 ]
	then
		printf '▌'
		exit
	fi

  if  [ "$m" -eq 0 ]
  then
    echo -n ' '
    exit
  fi

  for ((i=1; i<=m; i++))
  do
      echo -n '█'
  done
}

for d in `seq 29 -1 0`
do
  DAY=`date --date="-${d} days" +%u`
  DATE=`date --date="-${d} days" +%Y-%m-%d`
  COMMIT=`echo "$GIT_DAYS" | tr " " "\n" | grep "$DATE"`

  if [ "$COMMIT" = "$DATE" ]
  then
    STREAK="$green▣"
    let LAST_COMMIT++
  else
    STREAK="$white□"
    let LAST_NO_COMMIT++
  fi

  [[ $DAY -eq 6 ]] && BAR=${BAR}' '
  [[ $DAY -eq 1 ]] && BAR=${BAR}' '

  BAR=${BAR}${STREAK}
done

BAR_COMMIT=`bar "$LAST_COMMIT" 30`
BAR_NO_COMMIT=`bar "$LAST_NO_COMMIT" 30`
BAR_TREND="$green$BAR_COMMIT$red$BAR_NO_COMMIT"
TREND=`printf "%02d %s %02d" "$LAST_COMMIT" "$BAR_TREND" "$LAST_NO_COMMIT"`
echo "$BAR $TREND $white"

