#!/bin/bash

TMP1='/tmp/.git-repos.1.tmp'
TMP2='/tmp/.git-repos.2.tmp'
TMP3='/tmp/.git-repos.3.tmp'
REPOS="$HOME/.git-repos"

> "$TMP1"
> "$TMP2"

sort -k1 "$REPOS" | sort -u | while read n r
do
  dir=$(echo "$n" | grep -o / | head -1)
  if [ "$dir" = "/" ]
  then
    printf "%-52s %s\n" "$n" "$r" >> "$TMP1"
  else
    printf "%-52s %s\n" "$n" "$r" >> "$TMP2"
  fi
done

sort -u "$TMP1"  > "$REPOS"
sort -u "$TMP2" >> "$REPOS"
rm -f "$TMP1" "$TMP2"

