#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

[[ -n "$ORIGIN"  ]] || ORIGIN='origin'
[[ -z "$1"       ]] || ORIGIN="$1"
[[ -n "$GET_ALL" ]] && GET_ALL='--all'
[[ -n "$FILTER"  ]] || FILTER='.*'
[[ -z "$2"       ]] || FILTER="$2"

git remote get-url "$ORIGIN" $GET_ALL      \
  | sed 's/[a-z\-]\+:[a-zA-Z0-9_\-]\+@//g' \
  | grep -E "$FILTER"
