#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2020 Osiris Alejandro Gomez <osiris@gcoop.coop>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# shellcheck disable=SC1091
# shellcheck disable=SC1090
# shellcheck source=/dev/null
# shellcheck disable=SC2035

DIR_BIN=$(dirname "$0") && source "$DIR_BIN/git-src-common"

function usage()
{
cat << EOF
Usage:

\`\`\`bash

  $BIN

\`\`\`

Check syntax using shellcheck. Group errors by code in result.

Example:

\`\`\`bash

  $BIN

git-branch-checkout                           SC2124
git-branch-find                               SC2185
git-changelog                                 SC2059 SC2086

\`\`\`

EOF
exit 0
}

[[ "$1" =~ ^[-]+(h|help) ]] && usage

TMP="$(mktemp)"
FILES="$(mktemp)"
ERRORS=0

file --mime-type * | grep shellscript | tr -d ':' > "$FILES"

while read -r FILE _
do

if ! shellcheck "$FILE" > "$TMP"
then

  SC="$(grep -Eo 'SC[0-9]+' "$TMP" | sort -u | tr '\n' ' ')"
  printf "%-45s %s\n" "$FILE" "$SC"
  ERRORS="$((ERRORS+1))"

fi

done < "$FILES"

rm -f "$TMP"
rm -f "$FILES"

exit "$ERRORS"
