#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2021 Osiris Alejandro Gomez <osiux@osiux.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

TMP="$(mktemp)"


git-log-files                                    \
  | grep -E '[0-9]{4}-[0-9]{2}-[0-9]{2}-.*\.org' \
  | while read -r FILE
do

  SUBJECT="$(git log -1 --pretty=format:%s)"
  [[ "$SUBJECT" = "ChangeLog: $FILE" ]] && exit

  git-log-org-changelog "$FILE"

MSG="$(cat << EOF
ChangeLog: $FILE

  @ 00:00 hs
EOF
)"

  echo "$MSG" > "$TMP"
  git add "$FILE" && git commit -F "$TMP"

done

rm -f "$TMP"
