#!/bin/bash

# This script comes with ABSOLUTELY NO WARRANTY, use at own risk
# Copyright (C) 2017 Osiris Alejandro Gomez <osiux@osiux.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

TODAY="$(date '+%F')"

[[ -z "$1" ]] && exit 1
S1="$(date -d "$TODAY $1" '+%s')"

if [[ -z "$2" ]]
then
  S2="$(date -d "now" '+%s')"
else
  S2="$(date -d "$TODAY $2" '+%s')"
fi

if [[ "$S1" -gt "$S2" ]]
then
  D1="$(date -u -d "@$S2" +"%s")"
  D2="$(date -u -d "@$S1" +"%s")"
else
  D1="$(date -u -d "@$S1" +"%s")"
  D2="$(date -u -d "@$S2" +"%s")"
fi

date -u -d "0 $D2 sec - $D1 sec" +"%H:%M"
